### ISSUE TITLE
"Package cl is deprecated" warning

### ISSUE THREAD

**Issue by kitebuggy** [eschulte/rinari#93]
As of emacs 27.1, cl is being deprecated in favour of cl-lib.  This is causing issues with a number of other packages too, e.g. https://github.com/kiwanami/emacs-epc/issues/35

Any plans to remedy or is this Rinari package considered EOL?

Thanks

**Comment by purcell** [comment]
It's six years since the last commit, and I (as the most active maintainer) switched to `projectile-rails` a while back, so I think you should consider this package defunct.

If I were to fix the byte compilation warning it might give the false impression that this is actively maintained, but I suppose I'd consider a pull request if you care enough. :-)

**Comment by kitebuggy** [comment]
body{font-family:Helvetica,Arial;font-size:13px}Hi Steve,Thanks, I’ll give projectile-rails a go.  Keep up the great work!   On 15 December 2020 at 00:32:49, Steve Purcell (notifications@github.com) wrote: 
It's six years since the last commit, and I (as the most active maintainer) switched to projectile-rails a while back, so I think you should consider this package defunct.
If I were to fix the byte compilation warning it might give the false impression that this is actively maintained, but I suppose I'd consider a pull request if you care enough. :-)

**Comment by ShawnOtis** [comment]
If this isn't maintained anymore, should we specify it and the suggested alternative in the readme?

**Comment by purcell** [comment]
Done, thanks.
